baseURL = "http://jenmjones.com/" # Replace with your actual GitHub Pages URL

title = "Jen M Jones"
theme = "PaperMod"
languageCode = "en-us"
enableGitInfo = true  # Tracks last modified date of files

# Raw Data AI April 25, 2025 Copilot helped debug
[markup.goldmark.renderer]
  unsafe = true

# Suppress warnings related to partials AI April 25, 2025 Copilot helped debug
ignoreLogs = ['warning-partial-superfluous-prefix']

[pagination] 
pagerSize = 5

[params]
author = "Jen Jones"
description = "Exploring the rise and impact of textile mills."
showReadingTime = true
showToc = true  # Enables Table of Contents for posts
defaultTheme = "light"  # Options: light/dark/auto
disableThemeToggle = true
enableCover = true
cover = "images/banner.jpg" # Corrected typo in the folder name
coverSize = "full"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Blog"
url = "/blog/"
weight = 2

[[menu.main]]
name = "About"
url = "/about/"
weight = 3

[[menu.main]]
name = "CV"
url = "/CV/"
weight = 4

[[menu.main]]
name = "Research Projects"
url = "/research/"
weight = 5
