baseURL = "https://jenmjones.github.io/portfolio/jj-site"


title = "Jen M. Jones Portfolio"
theme = "PaperMod"
languageCode = "en-us"
enableGitInfo = true 


# Raw Data AI April 25, 2025 Copilot helped debug
[markup.goldmark.renderer]
  unsafe = true

#Clean URL AI April 25, 2025 Copilot help to deploy
relativeURLs = true

#To Handle pretty URLS AI April 25, 2025 Coplit
uglyURLs = true


# Suppress warnings related to partials AI April 25, 2025 Copilot helped debug
ignoreLogs = ['warning-partial-superfluous-prefix']

[pagination] 
pagerSize = 5

[params]
author = "Jen Jones"
description = "Exploring the rise and impact of textile mills."
showReadingTime = true
showToc = true  # Enables Table of Contents for posts
defaultTheme = "light"  # Options: light/dark/auto
disableThemeToggle = true
enableCover = true
cover = "images/banner.jpg" # Corrected typo in the folder name
coverSize = "full"

#My menu

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Blog"
url = "https://jenmjones.github.io/portfolio/jj-site/blog.html"
weight = 2

[[menu.main]]
name = "About"
url = "https://jenmjones.github.io/portfolio/jj-site/about.html"
weight = 3

[[menu.main]]
name = "CV"
url = "https://jenmjones.github.io/portfolio/jj-site/CV.html"
weight = 4

[[menu.main]]
name = "Research Projects"
url = "https://jenmjones.github.io/portfolio/jj-site/research.html"
weight = 5
